language: java
jdk:
- openjdk8

branches:
  only:
  - master

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
- zip -r I-am-Full-Stack *
- mkdir -p deploy
- mv I-am-Full-Stack.zip deploy/I-am-Full-Stack.zip

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: todolist-deploy
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  local_dir: deploy
  wait-until-deployed: true
  on:
    repo: jinusong/I-am-Full-Stack
    branch: master

- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: todolist-deploy
  key: I-am-Full-Stack.zip
  bundle_type: zip
  application: todolist
  deployment_group: todolist-group
  region: ap-northeast-2
  wait-until-deployed: true
  on:
    repo: jinusong/I-am-Full-Stack
    branch: master

notifications:
  email:
    recipients:
    - sugwer7464@gmail.com